### ISSUE TITLE
Kill region not working for me in vscode-1.24.0

### ISSUE THREAD

**Issue by paulkoerbitz** [rkwan94/vscode-emacs#1]
First of all let me say thank you very much for this fantastic extension which I have been using very happily for probably more than a year! Thank you!!!

I have an issue where the kill region command (shortcut Ctrl-w) is not working for me anymore in vscode-1.24.0.

How to reproduce
- Use the vscode-emacs mode
- select a region 
- Press Ctrl-w

What should happen
- The selected region should get deleted

What should happen instead
- The line where the cursor is (typically after the region) gets deleted, the region stays.

I realize that this is not a terribly good bug report, I'm happy to provide more details. I would mostly like to known whether others are experiencing the same problem or if its just me.

**Comment by rkwan94** [comment]
Thanks for the report,

I've tried to recreate this issue on my work and personal computers, one has Mac OS High Sierra with VSCode 1.24.0 and one has Windows 10 Creator's Update with VSCode 1.24.1, but mine works as expected on both.

Try upgrading to VSCode 1.24.1, but if you're still seeing the issue, feel free to send over the OS you're running, as well as any other extensions and keymaps you have active (Look for 'Developer: Inspect Key Mappings' in the command palette).

**Comment by lmcapser** [comment]
I'm seeing this same issue - vscode 24.1 on Linux CentOS-7 AND Windows-10.  I think I've been seeing this issue since the 1.24 update.  I'm attaching the "inspect key bindings" from the Windows-10 host.

I've also noticed that the Ctrl-V (emacs scroll down one page) appears to function as (paste) as well.

[vscode-key-mappings.txt](https://github.com/rkwan94/vscode-emacs/files/2129121/vscode-key-mappings.txt)

Hope this helps.

Thanks,
Lance

**Comment by rkwan94** [comment]
I've patched both those bugs now in this new release (v1.0.3).

@paulkoerbitz, @lmcapser please let me know if you still see these issues after updating this extension

**Comment by lmcapser** [comment]
I've updated to the 1.0.3 version and confirmed it's working for me on Linux and Windows10.

Thanks for the fix and the quick response!!

**Comment by paulkoerbitz** [comment]
Also updated and works great for me as well. Thank you so much!!
