### ISSUE TITLE
rectangle kill and yank

### ISSUE THREAD

**Issue by wallybarnum** [rkwan94/vscode-emacs#2]
Hello, 
I am not seeing the keybindings for kill-rectangle and yank-rectangle in this extension, the extension description implies that the functionality should be there.
I'm used to doing this to kill and yank rectangles of text:
C-x r k
and
C-x r y

Am I missing something?

Thanks for your contribution,
Wally

**Comment by rkwan94** [comment]
You'll need to activate rectangle mark mode first with C-x Space. Then you can use those keybindings. However, there's currently a bug with kill-rectangle (it will only kill the first line in the rectangle, however the entire rectangle is still added to the kill ring). Yank and save should work fine though.

Look out for v1.0.5 in the coming days for a fix to the rectangle-kill bug!

**Comment by wallybarnum** [comment]
excellent, thanks!
