### ISSUE TITLE
"Previous command was not a yank"

### ISSUE THREAD

**Issue by olagrottvik** [rkwan94/vscode-emacs#7]
If I'm yanking a region, I cannot pop another yank, I instead get the message:
"Previous command was not a yank"

However, killing multiple lines with C-w and poping them works fine.

I'm using VS Code 1.26.1, and vscode-emacs 1.0.5.

Steps to reproduce:
1. Mark region
2. Kill-region (C-w)
3. Mark another region
4. Kill-region
5. Yank (C-y)
6. Pop (M-y)

**Comment by olagrottvik** [comment]
I just noticed that a Pull request has been posted to fix this issue: #6 
Please merge, and close this issue.

**Comment by rkwan94** [comment]
Merged and published up to VS Marketplace
